# Generated by Django 3.2.9 on 2022-04-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardss', '0002_rename_image_post_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
