# Generated by Django 4.0.4 on 2022-04-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardss', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
