# Generated by Django 3.2.9 on 2022-04-12 07:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardss', '0008_alter_post_user_alter_profile_user_alter_rating_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='preview.png', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='preview.png', max_length=255, verbose_name='image'),
        ),
    ]
